// Bottom Info Bar — build script
// 1) copy src/host.js -> lib/index.js（ESM host 插件）
// 2) wrap src/client-bundle.js -> lib/client.js（client-modules 经典脚本 bundle）
//    包装形态与官方 client 包一致：window.__ModuleLoader__.load({ id, factory })
// 3) 构建时注入共享常量：从 constants.js 读取 SUBSCRIPTION_PROVIDERS / BILLING_PROVIDERS，替换锚点占位
// 用法：node scripts/build.mjs（package.json build/prepack 均调用）
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(fileURLToPath(new URL('../package.json', import.meta.url)))
const libDir = join(root, 'lib')

await rm(libDir, { recursive: true, force: true })
await mkdir(libDir, { recursive: true })

// 从 constants.js 读取单一生源的共享常量（v1.6：SUBSCRIPTION_PROVIDERS；v1.7：+BILLING_PROVIDERS）
const constantsSource = await readFile(join(root, 'src', 'constants.js'), 'utf8')
function extractArray(name) {
  const match = constantsSource.match(new RegExp('export const ' + name + ' = (\\[[\\s\\S]*?\\]);?'))
  if (!match) throw new Error('无法从 constants.js 中提取 ' + name)
  return match[1] // JS 数组字面量（构建后为 JSON 数组）
}
const subscriptionProvidersJson = extractArray('SUBSCRIPTION_PROVIDERS')
const billingProvidersJson = extractArray('BILLING_PROVIDERS')

// 1) host（ESM，原样复制后替换锚点占位）
let hostSource = await readFile(join(root, 'src', 'host.js'), 'utf8')
hostSource = hostSource.replace(/\/\*__SUBSCRIPTION_PROVIDERS__\*\/\[\]/g, subscriptionProvidersJson)
hostSource = hostSource.replace(/\/\*__BILLING_PROVIDERS__\*\/\[\]/g, billingProvidersJson)
await writeFile(join(libDir, 'index.js'), `// Generated by scripts/build.mjs from src/host.js — do not edit directly.\n${hostSource}`)

// 2) client（CJS 模块源 → __ModuleLoader__ bundle，替换锚点占位后包装）
let clientSource = await readFile(join(root, 'src', 'client-bundle.js'), 'utf8')
clientSource = clientSource.replace(/\/\*__SUBSCRIPTION_PROVIDERS__\*\/\[\]/g, subscriptionProvidersJson)
clientSource = clientSource.replace(/\/\*__BILLING_PROVIDERS__\*\/\[\]/g, billingProvidersJson)
const wrapped = [
  'window.__ModuleLoader__.load({ id: "dsh-bottom-info-bar", factory: (require) => {',
  'var module = { exports: {} }; var exports = module.exports;',
  clientSource,
  'return module.exports;',
  '} });',
  '',
].join('\n')
await writeFile(join(libDir, 'client.js'), wrapped)

console.log('build OK → lib/index.js, lib/client.js')