// Bottom Info Bar — build script
// 1) copy src/host.js -> lib/index.js（ESM host 插件）；copy src/constants.js -> lib/constants.js（host import 依赖）
// 2) wrap src/client-bundle.js + src/client-settings.js -> lib/client.js（client-modules 经典脚本 bundle）
//    包装形态与官方 client 包一致：window.__ModuleLoader__.load({ id, factory })
// 3) 构建时注入共享常量：从 constants.js 读取 SUBSCRIPTION_PROVIDERS / BILLING_PROVIDERS /
//    FIELD_REGISTRY / PRESET_COLOR_NAMES，替换源码中的锚点占位（client 为 CJS 无法 import，host 走真 import）
// 用法：node scripts/build.mjs（package.json build/prepack 均调用）
import { copyFile, mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(fileURLToPath(new URL('../package.json', import.meta.url)))
const libDir = join(root, 'lib')

await rm(libDir, { recursive: true, force: true })
await mkdir(libDir, { recursive: true })

// 从 constants.js 读取单一生源的共享常量（v1.6：SUBSCRIPTION_PROVIDERS；v1.7：+BILLING_PROVIDERS；
// v1.9：+FIELD_REGISTRY / PRESET_COLOR_NAMES）。数组/对象字面量按括号配对提取（注册表内嵌数组，非贪婪正则会截断）。
const constantsSource = await readFile(join(root, 'src', 'constants.js'), 'utf8')
function extractArray(name) {
  const marker = 'export const ' + name + ' = '
  const start = constantsSource.indexOf(marker)
  if (start === -1) throw new Error('无法从 constants.js 中找到 ' + name)
  const from = constantsSource.indexOf('[', start + marker.length)
  if (from === -1) throw new Error(name + ' 不是数组字面量')
  let depth = 0
  for (let i = from; i < constantsSource.length; i++) {
    const ch = constantsSource[i]
    if (ch === '[') depth++
    else if (ch === ']') {
      depth--
      if (depth === 0) return constantsSource.slice(from, i + 1)
    }
  }
  throw new Error(name + ' 的数组字面量未闭合')
}
const subscriptionProvidersJson = extractArray('SUBSCRIPTION_PROVIDERS')
const billingProvidersJson = extractArray('BILLING_PROVIDERS')
const fieldRegistryJson = extractArray('FIELD_REGISTRY')
const presetColorsJson = extractArray('PRESET_COLOR_NAMES')
function injectSharedConstants(source) {
  return source
    .replace(/\/\*__SUBSCRIPTION_PROVIDERS__\*\/\[\]/g, subscriptionProvidersJson)
    .replace(/\/\*__BILLING_PROVIDERS__\*\/\[\]/g, billingProvidersJson)
    .replace(/\/\*__FIELD_REGISTRY__\*\/\[\]/g, fieldRegistryJson)
    .replace(/\/\*__PRESET_COLORS__\*\/\[\]/g, presetColorsJson)
}

// 1) host（ESM，原样复制后替换锚点占位；constants.js 随包复制供 import 解析）
let hostSource = await readFile(join(root, 'src', 'host.js'), 'utf8')
hostSource = injectSharedConstants(hostSource)
await writeFile(join(libDir, 'index.js'), `// Generated by scripts/build.mjs from src/host.js — do not edit directly.\n${hostSource}`)
await copyFile(join(root, 'src', 'constants.js'), join(libDir, 'constants.js'))

// 2) client（CJS 模块源 → __ModuleLoader__ bundle）：信息栏主包在前、设置页扩展在后，
//    同一 factory 作用域共享 React/rpc；设置页尾部包装 module.exports，在信息栏 apply 后注册 settings.section。
let clientSource = await readFile(join(root, 'src', 'client-bundle.js'), 'utf8')
let clientSettingsSource = await readFile(join(root, 'src', 'client-settings.js'), 'utf8')
clientSource = injectSharedConstants(clientSource)
clientSettingsSource = injectSharedConstants(clientSettingsSource)
const wrapped = [
  'window.__ModuleLoader__.load({ id: "dsh-bottom-info-bar", factory: (require) => {',
  'var module = { exports: {} }; var exports = module.exports;',
  clientSource,
  clientSettingsSource,
  'return module.exports;',
  '} });',
  '',
].join('\n')
await writeFile(join(libDir, 'client.js'), wrapped)

console.log('build OK → lib/index.js, lib/constants.js, lib/client.js')